Use Python3 print() syntax instead of Python2 print in README
cloudflare/python-cloudflare pull request #120
Opened 2021-08-02 13:14 UTC by ulikoehler

README.md and README.rst still use the old Python2
```
print "x"
```
syntax which causes error when copy & pasting the code into Python3.

This PR changes the print syntax in README to use
```
print("x")
```
Note that this syntax is fully compatible with recent versions of Python2 as well as all versions of Python3.

2021-08-02 13:18 UTC, mahtin commented
Oops. You're right. The code was updated quite done time ago; however, the README wasn't. I'll get this merged soon. Thank you.

2021-10-17 17:48 UTC, ulikoehler commented on README.md
> +    zones.length()
Ah, must have missed this. Thanks ! Will fix ASAP

2022-02-08 13:59 UTC, aioue requested changes

2022-02-08 13:59 UTC, aioue commented on README.md
> +    zones.length()
zones.length()
```suggestion
    print(zones.length())
    print(json.dumps(zones, indent=4, sort_keys=True))
```

2022-02-20 17:02 UTC, aioue approved these changes

2022-03-30 20:39 UTC, closed without merging